### PR TITLE
Update: Tweak Roshan Images for 7.33 (New Frontiers)

### PR DESCRIPTION
**Pull request by howiieb**
Change the roshan images for 7.33 to show cheese instead of shard. Maybe in the future I can use GSI to work out which side of the map he's on based on the time of day and, as a result, which item he's holding - that's an exercise for later I think though

### CODE REVIEW

**Comment by adrian-miasik** [comment]
Ooo many thanks for updating the assets! I need to re-read the patch notes I missed haha.

I'll look into getting this merged n updated for the next release. 👍

**Comment by howiieb** [comment]
> Ooo many thanks for updating the assets! I need to re-read the patch notes I missed haha.
> 
> I'll look into getting this merged n updated for the next release. 👍

A lot has happened in the last few months and Roshan has become an awful lot more complicated! With him being in different locations and carrying different items based on the day or night, you can now know for certain whether he'll have a scepter or refresher and could even provide pointers on where he'll be on the map (as this is already shown on the minimap via lit-up pit icons, it isn't really cheating either). Ultimately a comprehensive update would take some time and effort, but the current graphics carry the meaning that it could be either a scepter or refresher drop well enough right now so just getting rid of the Shard is at least a more accurate look!

**Comment by adrian-miasik** [comment]
Alright, I've went through the patch notes and am caught up to speed.

Appreciate you pointing out what still needs to be tweaked for the future. But yes, very much agreed: A more comprehensive update to improve the Roshan timer visuals would be ideal. I'll open up a PR highlighting/discussing what will probably need to be done for that.

As for this PR, I'll merge your changes in and push out a new release before working on a more through update.
The assets are looking great. They look pixel perfect! 👍 

Thanks for your contribution!

**Comment by adrian-miasik** [comment]
You can install the new plugin locally here: https://github.com/adrian-miasik/stream-deck-plugins-dota-2/releases/download/v1.3.1/com.adrian-miasik.sdpdota2.streamDeckPlugin

I'll be submitting this to Elgato, so expect the update to appear on the store shortly.

**Pull request merged**
